# Original files

# FROM python:3.10-bullseye
# RUN python -m pip install --upgrade pip
# ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
# RUN chmod +x /wait
# WORKDIR /deps
# COPY requirements.txt requirements.txt
# RUN python -m pip install -r requirements.txt
# WORKDIR /app
# CMD /wait && uvicorn main:app --reload --host 0.0.0.0

# If you're using a relational database and want migrations
# to be run automatically, delete the previous CMD line and
# uncomment this CMD line
# CMD /wait && python -m migrations up && uvicorn main:app --reload --host 0.0.0.0




# # # Temp files Phat Made


FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
WORKDIR /deps
# Might need to change this to
# WORKDIR /app
COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt
WORKDIR /app
CMD /wait && uvicorn main:app --reload --host 0.0.0.0 --port 8000

# If you're using a relational database and want migrations
# to be run automatically, delete the previous CMD line and
# uncomment this CMD line
# original
# CMD /wait && python -m migrations up && uvicorn main:app --reload --host 0.0.0.0
# updated
# CMD /wait && python -m migrations up && uvicorn main:app --reload --host 0.0.0.0  --port 8000
